# Change these first
owner: DetegiCE
repo: gorakulist-uptime

sites:
  - name: GorakuList
    url: https://www.gorakulist.kr/
    assignees:
      - DetegiCE
      - irostub
      - SieR-VR
  - name: Google
    url: https://www.google.com
  - name: Imgur
    url: https://imgur.com/

status-website:
  cname: status.gorakulist.kr
  logoUrl: https://raw.githubusercontent.com/rainbow-flavor/GorakuList/master/gorakulist-client/src/main/resources/static/images/gl_logo.svg
  name: GorakuList Status
  theme: night
  introTitle: "GorakuList Status Page"
  introMessage: Is it healthy?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
